/**
 * @file src/types/analysis.ts
 * @description Shared TypeScript interfaces for the GitGuard AI analysis pipeline.
 *
 * These types flow across all Week-2 modules:
 *   contextBuilder → promptSanitizer → llmRouter → suggestionEnricher
 *   vulnerabilityScanner → reviewWorker → MongoDB Review model
 */

// ─── PR Context ───────────────────────────────────────────────────────────────

/**
 * Rich contextual information about a pull request, assembled by contextBuilder.
 * Injected into the LLM prompt so the model understands *why* the PR exists.
 */
export interface PRContext {
  /** PR number in the repository */
  prNumber: number;

  /** PR title */
  title: string;

  /** PR description/body (may be null) */
  description: string | null;

  /** Linked issue numbers extracted from the PR body (e.g. "Fixes #42") */
  linkedIssues: number[];

  /** Branch being merged from */
  headBranch: string;

  /** Branch being merged into */
  baseBranch: string;

  /** Primary language of the repository */
  language: string | null;

  /** Total number of changed files */
  changedFiles: number;

  /** Total lines added */
  additions: number;

  /** Total lines removed */
  deletions: number;

  /** Whether this is a draft PR */
  isDraft: boolean;

  /** Full repository name (owner/repo) */
  repositoryFullName: string;

  /** Name of the user who opened the PR */
  authorLogin: string;
}

// ─── Analysis Findings ────────────────────────────────────────────────────────

/** Severity levels aligned with OWASP / industry standard */
export type FindingSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

/** Category of a finding */
export type FindingCategory =
  | 'security'
  | 'bug'
  | 'performance'
  | 'code-quality'
  | 'dependency'
  | 'refactoring'
  | 'test-coverage';

/**
 * A single code review finding produced by the LLM or vulnerability scanner.
 */
export interface AnalysisFinding {
  /** File path relative to repo root */
  file: string;

  /** Line number in the diff (0 if file-level) */
  line: number;

  /** Severity of the issue */
  severity: FindingSeverity;

  /** Category of the issue */
  category: FindingCategory;

  /** Human-readable description of the issue */
  message: string;

  /** Suggested fix (may include a code block in Markdown) */
  suggestion: string;

  /** 0–1 confidence score from the LLM */
  confidence: number;

  /** Auto-generated test skeleton (added by suggestionEnricher, optional) */
  testSuggestion?: string;

  /** Auto-generated refactoring hint (added by suggestionEnricher, optional) */
  refactoringSuggestion?: string;
}

// ─── Vulnerability Findings ───────────────────────────────────────────────────

/** A dependency vulnerability finding from the vulnerability scanner */
export interface VulnerabilityFinding {
  /** Package name (e.g. "lodash") */
  packageName: string;

  /** Version string found in the diff */
  version: string;

  /** CVE ID if known */
  cveId?: string;

  /** Human-readable description */
  description: string;

  /** Severity level */
  severity: FindingSeverity;

  /** Suggested safe version to upgrade to */
  suggestedVersion?: string;

  /** Source of this finding */
  source: 'oss-index' | 'local-pattern';
}

// ─── Full Analysis Result ─────────────────────────────────────────────────────

/** The structured output of one complete AI review cycle */
export interface AnalysisResult {
  /** Correlates with the internal event ID from the webhook */
  eventId: string;

  /** Full repository name */
  repositoryFullName: string;

  /** PR number */
  prNumber: number;

  /** Summary narrative generated by the LLM */
  summary: string;

  /** All code review findings */
  findings: AnalysisFinding[];

  /** Dependency vulnerability findings */
  vulnerabilities: VulnerabilityFinding[];

  /** Aggregate severity counts */
  metrics: {
    critical: number;
    high: number;
    medium: number;
    low: number;
    info: number;
    totalFindings: number;
    vulnerabilitiesFound: number;
    codeQualityScore: number; // 0–100
  };

  /** Which LLM model produced this result */
  modelUsed: string;

  /** Number of retry attempts made */
  retryCount: number;

  /** Total LLM latency in milliseconds */
  llmLatencyMs: number;
}

// ─── Queue Job Payload ────────────────────────────────────────────────────────

/** The data shape enqueued into the BullMQ review-pr queue */
export interface ReviewJobPayload {
  /** Unique event ID (from webhook) for end-to-end correlation */
  eventId: string;

  /** Full repository name (owner/repo) */
  repositoryFullName: string;

  /** Repository owner login */
  ownerLogin: string;

  /** Repository name */
  repoName: string;

  /** PR number */
  prNumber: number;

  /** SHA of the head commit (used to post inline review) */
  headSha: string;

  /** Raw PR diff URL (from GitHub) */
  diffUrl: string;

  /** Optional raw diff content (used for manual testing/triggers) */
  rawDiff?: string;

  /** GitHub PAT or installation token — enables comment + label posting */
  githubToken?: string;

  /** Assembled PR context */
  context: PRContext;

  /** ISO timestamp when the job was enqueued */
  enqueuedAt: string;
}
