/**
 * @file src/types/express.d.ts
 * @description Extends the Express Request interface with custom properties
 * added by our middlewares.
 */

declare namespace Express {
  interface Request {
    /**
     * Unique identifier for this request — generated by the requestId middleware.
     * Propagated through all logs for distributed tracing.
     */
    id: string;

    /**
     * Raw Buffer body preserved by the rawBodyParser middleware.
     * Required for HMAC signature verification (must hash the exact bytes received).
     */
    rawBody?: Buffer;
  }
}
