/**
 * @file src/types/github.ts
 * @description TypeScript types for GitHub Pull Request webhook payloads.
 *
 * Based on GitHub REST API documentation:
 * https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request
 */

/** Supported pull_request event actions */
export type PullRequestAction = 'opened' | 'synchronize' | 'reopened';

/** All possible pull_request actions (for filtering unsupported ones) */
export type AnyPullRequestAction =
  | PullRequestAction
  | 'closed'
  | 'edited'
  | 'assigned'
  | 'unassigned'
  | 'labeled'
  | 'unlabeled'
  | 'review_requested'
  | 'review_request_removed'
  | 'ready_for_review'
  | 'locked'
  | 'unlocked'
  | 'auto_merge_enabled'
  | 'auto_merge_disabled'
  | string;

/** GitHub user/actor object */
export interface GitHubUser {
  login: string;
  id: number;
  avatar_url: string;
  html_url: string;
  type: 'User' | 'Bot' | 'Organization';
}

/** Repository information from the webhook payload */
export interface GitHubRepository {
  id: number;
  name: string;
  full_name: string;
  private: boolean;
  html_url: string;
  description: string | null;
  owner: GitHubUser;
  default_branch: string;
  language: string | null;
  clone_url: string;
}

/** Pull request head/base reference */
export interface GitHubRef {
  label: string;
  ref: string;
  sha: string;
  user: GitHubUser;
  repo: GitHubRepository;
}

/** Core pull request object */
export interface GitHubPullRequest {
  url: string;
  id: number;
  number: number;
  state: 'open' | 'closed';
  locked: boolean;
  title: string;
  body: string | null;
  html_url: string;
  diff_url: string;
  patch_url: string;
  created_at: string;
  updated_at: string;
  closed_at: string | null;
  merged_at: string | null;
  draft: boolean;
  user: GitHubUser;
  head: GitHubRef;
  base: GitHubRef;
  additions: number;
  deletions: number;
  changed_files: number;
  commits: number;
}

/** Raw GitHub pull_request webhook payload */
export interface GitHubWebhookPayload {
  action: AnyPullRequestAction;
  number: number;
  pull_request: GitHubPullRequest;
  repository: GitHubRepository;
  sender: GitHubUser;
  installation?: {
    id: number;
    node_id: string;
  };
  organization?: {
    login: string;
    id: number;
  };
  rawDiff?: string;
}

// ─── Internal Event Types ─────────────────────────────────────────────────────

/**
 * Clean internal representation of a pull request event.
 * This is what flows through our services — decoupled from the raw GitHub shape.
 */
export interface PullRequestEvent {
  /** Unique event ID generated by us for correlation */
  eventId: string;

  /** The specific action that triggered the event */
  action: PullRequestAction;

  /** Raw diff string, optionally provided directly to bypass large PR fetching errors */
  rawDiff?: string;

  /** Pull request metadata */
  pullRequest: {
    id: number;
    number: number;
    title: string;
    body: string | null;
    htmlUrl: string;
    diffUrl: string;
    state: 'open' | 'closed';
    isDraft: boolean;
    additions: number;
    deletions: number;
    changedFiles: number;
    commits: number;
    headRef: string;
    headSha: string;
    baseRef: string;
    baseSha: string;
    createdAt: string;
    updatedAt: string;
  };

  /** Repository metadata */
  repository: {
    id: number;
    name: string;
    fullName: string;
    isPrivate: boolean;
    htmlUrl: string;
    defaultBranch: string;
    language: string | null;
    ownerLogin: string;
  };

  /** Who triggered the event */
  sender: {
    login: string;
    id: number;
    avatarUrl: string;
    type: string;
  };

  /** Timestamps */
  receivedAt: Date;
}

/** Standard API response shape */
export interface ApiResponse<T = undefined> {
  success: boolean;
  message: string;
  eventId?: string;
  data?: T;
  error?: {
    code: string;
    details?: unknown;
  };
}
